### ISSUE TITLE
How can I specify the path of libxslt?

### ISSUE THREAD

**Issue by pangpangshui** [rpeyron/libxmldiff#3]
I cross compile this tool for arm， but it can't find the path of libxslt when configure? Some help?
@rpeyron

**Comment by rpeyron** [comment]
Hello, I am not accustomed to cross-compiling but I guess you will need libxslt/libexslt and libxml2 libraries cross-compiled for ARM. The current configure script does not allow you to specify the path of the libraries but you can specify it with CFLAGS / LDFLAGS environment variables (eg : "LDFLAGS=-L/mypath ./configure")

**Comment by pangpangshui** [comment]
1. Actually, I have try this way, but It didn't work. My configure order is:
`CPPFLAGS='-I/sda4/testpatchxml/libxslt-1.1.33/build/include'  LDFLAGS='-L/sda4/testpatchxml/libxslt-1.1.33/build/lib' ./configure CXXFLAGS=--std=c++11 --prefix=/sda4/testpatchxml/libxmldiff/build CC=aarch64-himix100-linux-gcc CXX=aarch64-himix100-linux-g++ --host=arm-linux --with-xml-prefix=/sda4/testpatchxml/libxml2-2.9.8/build --with-xml-exec-prefix=/sda4/testpatchxml/libxml2-2.9.8/build`

libxslt's  path is `/sda4/testpatchxml/libxslt-1.1.33/build/lib`.
Am I wrong?
@rpeyron 


2. Also when I compile it for x86-64, it can be compiled completely.
3. I can't find file named 'configure.in', so I can't add configuration of libxslt path to file 'configure'.

**Comment by pangpangshui** [comment]
I try to modify configure.ac and Makefile.am. If I succeed, I will share my results with you.

**Comment by rpeyron** [comment]
Hello, found that libxslt ships now a m4 file with AM_PATH_XSLT macro. It adds --with-xslt-prefix= and --with-xslt-exec-prefix= options that should answer to your problem. Modified in latest commit, please let me know if it does not fix your problem.

**Comment by Mailaender** [comment]
This problem still persists for me on @openSUSE:

```
[    7s] checking for libxslt - version >= 1.0.0... no
[    7s] *** Could not run libxslt test program, checking why...
[    7s] *** The test program failed to compile or link. See the file config.log for the
[    7s] *** exact error that occured. This usually means LIBXSLT was incorrectly installed
[    7s] *** or that you have moved LIBXSLT since it was installed. In the latter case, you
[    7s] *** may want to edit the xslt-config script: /usr/bin/xslt-config
[    7s] configure: error: libxslt must be installed.
```

libxslt-devel 1.1.32 is installed.

**Comment by rpeyron** [comment]
Hello, I have replaced the m4 tests with pkg-config to detect libraries. Just tested with opensuse 15.2, it should be OK now.

**Comment by Mailaender** [comment]
That fixed the build https://build.opensuse.org/package/show/home:Mailaender:branches:editors/libxmldiff however it does not produce any shared libraries.

**Comment by rpeyron** [comment]
Hello, the current build process produces only a static library (src/libxmldiff.a). If you need a shared library, I guess using _LTLIBRARIES instead of _LIBRARIES in src/Makefile.am should do the trick, but I have never tried.
