### ISSUE TITLE
Problems loading via apt-get

### ISSUE THREAD

**Issue by fyodorovich** [rpeyron/libxmldiff#4]
I'm getting errors when trying to install libxmldiff onto Ubuntu bionic.

`vagrant@bionic:~$ sudo apt-get update

Hit:1 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease

Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease

Hit:3 http://us.archive.ubuntu.com/ubuntu bionic InRelease

Hit:4 https://deb.nodesource.com/node_12.x bionic InRelease

Hit:5 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease

Hit:6 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease

Ign:7 http://www.lprp.fr/debian stable InRelease

Err:8 http://www.lprp.fr/debian stable Release

  404  Not Found [IP: 90.127.29.122 80]

Reading package lists... Done

E: The repository 'http://www.lprp.fr/debian stable Release' does not have a Release file.

N: Updating from such a repository can't be done securely, and is therefore disabled by default.

N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by rpeyron** [comment]
Hello,
With Ubuntu, please use the PPA: ppa:rpeyron/ppa  
Debian repository is not working anymore, I will remove it from doc.
Thanks for reporting.
