### ISSUE TITLE
Removing child element marks siblings as modified

### ISSUE THREAD

**Issue by drienkop** [rpeyron/libxmldiff#6]
Consider these two XML files:
**1.txt**
```
<class>
    <person>
        <name>Mick</name>
    </person>
    <person>
        <name>Jack</name>  
    </person>  
    <person>  
        <name>Brian</name>  
    </person>  
    <person>
        <name>Linda</name>  
    </person>  
</class>  
```
**2.txt**
```
<class>
  <person>
      <name>Mick</name>
  </person>
  <person>
      <name>Brian</name>
  </person>
  <person>
      <name>Linda</name>
  </person>  
</class>
```
`xmldiff diff 1.txt 2.txt out.txt`
produces the following file:
**out.txt**
```
<?xml version="1.0"?>
<class xmlns:diff="http://www.via.ecp.fr/~remi/soft/xml/xmldiff" diff:status="below">
  <person>
    <name>Mick</name>
  </person>
  <person diff:status="below">
    <name diff:status="modified">Jack|Brian</name>
  </person>
  <person diff:status="below">
    <name diff:status="modified">Brian|Linda</name>
  </person>
  <person diff:status="removed">
    <name diff:status="removed">Linda</name>
  </person>
</class>
```
As no change was done to the elements with name Brian and Linda, there is no reason to mark these two as modified. Furthermore element Linda is marked as removed, but it was the element Jack which was removed.

I would expect the **out.txt** file to be:
```<?xml version="1.0"?>
<class xmlns:diff="http://www.via.ecp.fr/~remi/soft/xml/xmldiff" diff:status="below">
<class>
  <person>
      <name>Mick</name>
  </person>
  <person diff:status="removed">
      <name diff:status="removed">Jack</name>
  </person>
  <person>
      <name>Brian</name>
  </person>
  <person>
      <name>Linda</name>
  </person>  
</class>
```

**Comment by rpeyron** [comment]
Hello, the algorithm of xmldiff is based on identifiers relevant to your files. Without identifiers, xmldiff will process the file only based on the position of nodes, giving what you observed.

For your files, the relevant identifier to use seems to be the value of the node 'name', so `xmldiff diff --ids name 1.xml 2.xml` will provide the result you expect

**Comment by drienkop** [comment]
Thank you, just what I was looking for!
